// CPR LaunchPad Template Config
// Every client-variable lives here. New client = new config, same layout.

export const site = {
  brand: {
    nameLine1: "CANADIAN PROSPECTS",
    nameLine2: "RECRUITMENT",
    tagline: "FINDING OPPORTUNITY. BUILDING FUTURES.",
    logo: "/cpr-logo.png",
  },
  colors: {
    red: "#B21712",
    redBright: "#C8102E",
    black: "#0C0C0A",
    dark: "#08090B",
    offWhite: "#F7F7F7",
    white: "#FFFFFF",
  },
  links: {
    apply: "/apply",
    video: "https://youtu.be/iqietCwnCxc",
    instagram: "https://instagram.com/mississaugamagic",
    instagramProspects: "https://instagram.com/prospects.ca",
    facebook: "https://www.facebook.com/mississaugamagic21",
  },
  nav: ["HOME", "ABOUT US", "HOW IT WORKS", "SUCCESS STORIES", "FAQ", "CONTACT"],
  hero: {
    line1: "YOUR NEXT",
    line2: "OPPORTUNITY",
    line3: "STARTS HERE.",
    sub: "We help Canadian student-athletes get noticed by college coaches and find the right school to compete and succeed.",
    image: "/hero-committed.jpg",
  },
  global: {
    heading: "Take the first step in making your Dreams a reality!",
    image: "/proof-canada.jpg",
    caption:
      "Canadian Prospects has gone Global! We now assist kids anywhere in the world in finding unbelievable opportunities to showcase their talents in multiple sports!",
  },
  process: {
    heading: ["OUR ", "RECRUITMENT", " PROCESS"],
    sub: "We make the recruiting process simple, organized and effective.",
    steps: [
      { n: "1. APPLY", d: "Complete your application and create your player profile.", icon: "apply" },
      { n: "2. UPLOAD", d: "Upload your mixtapes, YouTube links, pictures, teams and documents.", icon: "upload" },
      { n: "3. AGREEMENT", d: "Review and complete the Fee Structure Agreement to activate your profile.", icon: "agreement" },
      { n: "4. RECRUITING", d: "We send your profile to coaches and track responses.", icon: "recruiting" },
      { n: "5. OPPORTUNITIES", d: "We present real opportunities and guide you every step of the way.", icon: "opportunities" },
    ],
  },
  showcase: {
    heading: ["SHOWCASE", " YOUR TALENT"],
    sub: "Submit everything coaches need to evaluate you.",
    tiles: [
      { label: "Mixtapes / Game Film", icon: "film" },
      { label: "YouTube Links", icon: "youtube" },
      { label: "Photos", icon: "photos" },
      { label: "Teams", icon: "teams" },
      { label: "Transcripts", icon: "doc" },
      { label: "Report Cards", icon: "report" },
      { label: "Awards & Achievements", icon: "trophy" },
      { label: "Other Documents", icon: "folder" },
    ],
    cta: "START YOUR APPLICATION",
  },
  coachPanel: {
    heading: ["WHAT ", "COACHES", " RECEIVE"],
    sub: "A professional profile with the information they need.",
    athlete: {
      name: "JAYDEN THOMPSON",
      meta: "Point Guard  |  6'2\"  |  175 lbs  |  Class of 2026",
      team: "Mississauga Magic U18 AAA",
      photo: "/jayden-photo.png",
      rows: [
        ["GPA", "3.8"],
        ["SAT (Est.)", "1180"],
        ["Position", "PG"],
        ["High School", "Lorne Park SS"],
      ],
      videos: ["/video-main.png", "/video-2.png", "/video-3.png"],
    },
    cta: "VIEW SAMPLE PROFILE",
  },
  camps: {
    eyebrow: "CAMPS & EXPOSURE",
    heading: ["CAMPS THAT PUT ", "DEVELOPMENT", " IN MOTION"],
    tagline: "A Play To Win!",
    sub: "From skill development camps to national showcases, CPR athletes train, compete, and get seen by the right coaches at the right events.",
    cta: "START YOUR APPLICATION",
    slides: [
      { img: "/hero-athlete.png", caption: "CPR athletes sharpening skills on the court." },
      { img: "/proof-team.jpg", caption: "Team camps that build chemistry and competition." },
      { img: "/proof-canada.jpg", caption: "Exposure on national and international stages." },
    ],
  },
  winning: {
    eyebrow: "CHAMPIONSHIP MINDSET",
    heading: ["WINNING IS A ", "STANDARD", ", NOT A SLOGAN"],
    sub: "We develop athletes who compete with purpose — on the court, in the classroom, and in the recruiting process.",
    cta: "APPLY NOW",
    slides: [
      { img: "/proof-champion.jpg", caption: "From CPR to conference championships." },
      { img: "/hero-committed.jpg", caption: "Committed athletes. Serious results." },
      { img: "/proof-canada.jpg", caption: "Representing Canada at the highest level." },
    ],
  },
  track: {
    heading: ["WE ", "TRACK", ". YOU STAY INFORMED."],
    sub: "We manage the outreach. You see the results.",
    features: [
      { t: "Coach Outreach", d: "We send your profile to the right coaches and programs.", icon: "send" },
      { t: "Opportunity Management", d: "We help you manage interest, visits and offers.", icon: "manage" },
      { t: "Response Tracking", d: "Track opens, views and responses from coaches.", icon: "trackicon" },
      { t: "Real-Time Updates", d: "Your dashboard keeps you updated every step of the way.", icon: "updates" },
      { t: "School Interest", d: "See which schools are interested in you.", icon: "school" },
      { t: "Secure & Private", d: "Your information is safe and only shared with coaches.", icon: "lock" },
    ],
    image: "/dashboard.png",
  },
  stats: [
    { v: "500+", l: "ATHLETES ASSISTED" },
    { v: "1,000+", l: "COACH CONTACTS MADE" },
    { v: "250+", l: "SCHOOLS REACHED" },
    { v: "$25M+", l: "IN SCHOLARSHIP OPPORTUNITIES" },
  ],
  stories: {
    heading: "SUCCESS STORIES",
    items: [
      { img: "/proof-canada.jpg", caption: "CPR athlete competing for Team Canada." },
      { img: "/proof-champion.jpg", caption: "From CPR to a conference championship." },
      { img: "/proof-team.jpg", caption: "CPR athletes showcasing at the next level." },
    ],
  },
  tribute: {
    eyebrow: "IN MEMORIAM",
    name: "GEORGE RAVELING",
    meta: "Basketball Hall of Fame · Class of 2015 · 1937 – 2025",
    message: [
      "If we are lucky, we get to meet not only great men but good men. To have one man be both is extremely rare.",
      "In memory of one of the best human beings I've ever met. We can only try to stand on the shoulders of true giants.",
      "You are missed.",
    ],
    sign: "— Mike, Canadian Prospects Recruitment",
    slides: [
      { img: "/tribute/raveling-memorial.png", caption: "George Raveling — Basketball Hall of Fame, Class of 2015." },
      { img: "/tribute/raveling-hall-of-fame.png", caption: "George Raveling at the Basketball Hall of Fame." },
      { img: "/tribute/raveling-bill-russell.png", caption: "George Raveling with Bill Russell." },
      { img: "/tribute/raveling-coaching-youth.png", caption: "Passing wisdom to the next generation." },
      { img: "/tribute/raveling-gym-session.png", caption: "Teaching, mentoring, and leading on the court." },
      { img: "/tribute/raveling-mentoring.png", caption: "A lifetime of mentorship and impact." },
      { img: "/tribute/raveling-team.png", caption: "Standing with the athletes he believed in." },
      { img: "/tribute/raveling-portrait.png", caption: "George Raveling." },
      { img: "/tribute/raveling-family.png", caption: "Surrounded by those he lifted up." },
      { img: "/tribute/raveling-dinner.png", caption: "A great man and a good man." },
    ],
  },
  cta: {
    heading: "READY TO TAKE THE NEXT STEP?",
    sub: "Start your application today and take control of your future.",
    button: "APPLY NOW",
  },
  footer: {
    about: "We connect Canadian student-athletes with opportunities to play basketball at the next level.",
    quickLinks: ["About Us", "How It Works", "Success Stories", "FAQ", "Contact"],
    resources: ["For Athletes", "For Parents", "NCAA Recruiting Guide", "Fee Agreement"],
    email: "mikecrpglobal@mississaugamagic.com",
    instagramLabel: "@mississaugamagic",
    prospectsInstagramLabel: "@Prospects.ca",
    location: "Mississauga, Ontario",
    copyright: "© 2026 Canadian Prospects Recruitment. All Rights Reserved.",
  },
};
